version: '3.8'

services:
  novy_spev:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./songs:/app/songs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    env_file:
      - .env
    restart: unless-stopped
